export { default as Header } from '../components/header/Header'
export { default as Footer } from '../components/footer/Footer'
export { default as CarouselPersonal } from '../components/carousel/Carousel'
export { default as InfoContent} from '../components/infocontent/InfoContent'
export { default as Agendamento } from '../components/agendamento/Agendamento'